### ISSUE TITLE
index.html isn't working properly and the content is not centred. Add me as a contributor.

### ISSUE THREAD

**Issue by ghost** [JediRhymeTrix/KMIT_IMS#2]
index.html isn't working and the content is not centred. And btw add me as a contributor.

**Comment by JediRhymeTrix** [comment]
Fixed.

Refer to commit [https://github.com/JediRhymeTrix/KMIT_IMS/commit/9c20c5d2cc69d15e80e1c02bb4d2abe59fe3fc86](url)
